// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grjebniqxxpeijtfgrbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyamVibmlxeHhwZWlqdGZncmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODQ1NjAsImV4cCI6MjA2NzA2MDU2MH0.w2WVMtDZ0eSW0lH3qGbC9Q7H6fSU3CY7YzzDFYBYGck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});